[manager]
ratio = [1, 4, 3]
sort_by = "extension"
set_dir_first = true
show_symlink = true
scrolloff = 10
linemode = "mtime"

[opener]
open = [
  { run = 'nvim "$@"',                      block = true,         desc = "neovim"      },
  { run = 'zeditor "$@"',                   orphan = true,        desc = "Zed"         },
]                                           
edit = [                                    
  { run = 'nvim "$@"',                      block = true,         desc = "neovim"      },
  { run = 'zeditor "$@"',                   orphan = true,        desc = "Zed"         },
]                                           
pdf = [                                     
  { run = 'zathura "$@"',                   orphan = true,        desc = "zathura"     },
  { run = 'zen-browser "$@"',               orphan = true,        desc = "Zen Browser" },
  { run = 'libreoffice "$@"',               orphan = true,        desc = "LibreOffice" },
  { run = 'librewolf "$@"',                 orphan = true,        desc = "LibreWolf"   },
]                                           
video = [                                   
  { run = 'mpv "$@"',                       orphan = true,        desc = "mpv"         },
  { run = 'libreoffice "$@"',               orphan = true,        desc = "LibreOffice" },
]                                           
audio = [                                   
  { run = 'mpv "$@"',                       orphan = true,        desc = "mpv"         },
  { run = 'libreoffice "$@"',               orphan = true,        desc = "LibreOffice" },
]                                           
image = [                                   
  { run = 'xdg-open "$@"',                  orphan = true,        desc = "swayimg"     },
  { run = 'swayimg "$@"',                   orphan = true,        desc = "swayimg"     },
  { run = 'libreoffice "$@"',               orphan = true,        desc = "LibreOffice" },
]                                           
office = [                                  
  { run = 'libreoffice "$@"',               orphan = true,        desc = "LibreOffice" },
  { run = 'zen-browser "$@"',               orphan = true,        desc = "Zen Browser" },
  { run = 'librewolf "$@"',                 orphan = true,        desc = "LibreWolf"   },
]                                           
directory = [
  { run = 'foot -D "$@"',                   orphan = true,        desc = "terminal"    },
  { run = 'nvim "$@"',                      block = true,         desc = "neovim"      },
  { run = 'foot -e yazi "$@"',              orphan = true,        desc = "yazi"        },
  { run = 'zeditor "$@"',                   orphan = true,        desc = "Zed"         },
]
                                            
[open]                                      
rules = [                                   
  { mime = "inode/directory",               use = [ "directory" ] },
  { mime = "text/*",                        use = [ "edit"      ] },
  { mime = "application/json",              use = [ "edit"      ] },
  { mime = "video/*",                       use = [ "video"     ] },
  { mime = "audio/*",                       use = [ "audio"     ] },
  { mime = "image/*",                       use = [ "image"     ] },
  { mime = "application/pdf",               use = [ "pdf"       ] },
                                            
  # Microsoft Office Filetypes              
  { mime = "application/msword",            use = [ "office"    ] },
  { mime = "application/vnd.ms*",           use = [ "office"    ] },
  { mime = "application/vnd.openx*",        use = [ "office"    ] },
  
  # Open Document Filetypes
  { mime = "application/vnd.oasis.opend*",  use = [ "office"    ] },
]
